jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
  - name: BuildConfiguration
    value: release
  - group: BUILD Management Resources
  workspace:
      clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-forecasting-jobs
      ContinueOnVulnerablePackageScanError: true

  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Function Forecasting Triggeres'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Forecasting.Triggers/SFA.DAS.Forecasting.Triggers.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Function Forecasting Commitments'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Forecasting.Commitments.Functions/SFA.DAS.Forecasting.Commitments.Functions.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact - ForecastingJobs'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'
      artifactName: ${{ parameters.SolutionBaseName }}